### ISSUE TITLE
Error when create project using buckbonejava

### ISSUE THREAD

**Issue by cwicaksono** [zserge/buckbone#5]
I try using buckbonejava but when I try to create sandbox project using that, it show message like this

<pre>
buckbonejava com.example.app bucksample
base64: invalid option -- d
Usage:  base64 [-dhvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
</pre>

**Comment by damianoneill** [comment]
I assume your using OSX, if so edit the downloaded file and remove the -d option from the base64 command, this allows it to complete.
